spring:
  application:
    name: idv-one-time-passcode
  main:
    banner-mode: off

info:
  app:
    name: ${spring.application.name}
    
management:
  endpoint:
    health:
      show-details: always