spring:
  application:
    name: idv-one-time-passcode
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwk-set-uri: https://michaelruocco.eu.auth0.com/.well-known/jwks.json
        jwt:
          audience: https://idv-demo-api
          issuer: https://michaelruocco.eu.auth0.com/
          subjects: test-client-id

management:
  endpoints:
    web.exposure.include: health,info
  endpoint:
    health:
      show-details: always