spring:
  application:
    name: idv-one-time-passcode
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://michaelruocco.eu.auth0.com/

info:
  app:
    name: ${spring.application.name}
    
management:
  endpoint:
    health:
      show-details: always

auth0:
  audience: https://idv-demo-api

