version: '3'
services:

  elk:
    image: sebp/elk
    container_name: elk
    ports:
      - 5601:5601
    volumes:
      - ./elastic/logstash/pipeline.conf:/etc/logstash/conf.d/pipeline.conf:ro

  filebeat:
    image: elastic/filebeat:7.9.3
    container_name: filebeat
    restart: on-failure
    user: root
    volumes:
      - ./elastic/filebeat/docker.filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - elk

  aws-sns:
    image: localstack/localstack:latest
    container_name: aws-sns
    environment:
      - DEFAULT_REGION=eu-west-1
      - SERVICES=sns

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: welcome
      MONGO_INITDB_DATABASE: idv-local
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  one-time-passcode-app:
    image: michaelruocco/one-time-passcode-spring-app
    container_name: one-time-passcode-app
    mem_limit: 2048m
    mem_reservation: 2048m
    ports:
      - 8081:80
    environment:
      - SERVER_PORT=80
      - SPRING_PROFILES_ACTIVE=simple-logging
      - AWS_ACCESS_KEY=abc
      - AWS_SECRET_KEY=123
      - AWS_SNS_ENDPOINT_URI=http://aws-sns:4566
      - MONGO_CONNECTION_STRING=mongodb://idv:welcome01@mongo:27017/idv-local
      - REQUEST_LOGGING_ENABLED=true
      - RESPONSE_LOGGING_ENABLED=true
    depends_on:
      - aws-sns
      - mongo